name: OpenWRT-R4S

on:
  #schedule:
  #  - cron: '00 10 * * *'
  watch:
   types: started

jobs:
  build:
    name: Build OpenWRT
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Init Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          
      - name: Get Source Code
        run: |
          git clone https://github.com/coolsnowwolf/lede.git
          git clone https://github.com/TorBoxCode/luci-app-eqos lede/package/lean/luci-app-eqos
          git clone https://github.com/TorBoxCode/luci-app-tencentddns lede/package/lean/luci-app-tencentddns
          git clone https://github.com/frainzy1477/luci-app-trojan lede/package/lean/luci-app-trojan
          git clone https://github.com/frainzy1477/luci-app-clash lede/package/lean/luci-app-clash
          sed -i '$a\src-git helloworld https://github.com/fw876/helloworld' lede/feeds.conf.default
          cd lede/
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Custom Configuration
        run: |
          cp -f All/CONFIG_R4S.ini lede/.config
          chmod +x All/Customize.sh && sh All/Customize.sh
      
      - name: Build OpenWRT
        run: |
          cd lede/
          make defconfig
          make download -j8
          make -j$(nproc) || make -j1 V=s
      
      - name: Prepare Artifact
        run: find lede/bin/targets/ -type d -name "packages" | xargs rm -rf {}
          
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: OpenWRT-R4S
          path: lede/bin/targets/
          #rockchip/armv8/
